### ISSUE TITLE
[Feature Request] Make mod work with other mods

### ISSUE THREAD

**Issue by Fuxy22** [SeaRyanC/fast-filter-fill#4]
Can you make your mod work with other mods that introduce larger cargo wagons like say Bob's Mods.

That would be really awesome.

At the moment it only filters the slots you would have on a regular wagon leaving the extra ones blank.

**Comment by SeaRyanC** [comment]
I'm not able to make updates at this time but it should be a pretty easy fix for a PR -- there's one spot in the code where I "calculate" the length (using a lookup switch) where I didn't realize LUA's length operator `#` is the correct thing to use.

**Comment by Fuxy22** [comment]
Oh I just noticed it seems to be done in the github code just not in version 0.5.2 that is downloaded.

Just needs a version bump and release.

**Comment by Fuxy22** [comment]
I bumped the version added a release on the releases folder updated the link in the README tagged the release and also added the release here https://github.com/Fuxy22/fast-filter-fill/releases .

Not sure if that will get merged with a PR but tag should at least.

**Comment by keryja** [comment]
Fast Filter Fill has now been published on the [mod portal](https://mods.factorio.com/mods/Keryja/fast-filter-fill) by me, and these changes should be in that as well, so this issue can be closed.
