### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by keryja** [SeaRyanC/fast-filter-fill#7]
I'm currently working on rewriting and updating fast-filter-fill to work with 0.14 and more than just cargo wagons.

However as there's currently no license file present your code is not allowed to be used or modified, hence I would not be able to release the changes (and technically shouldn't've even touched it).

I recommend the MIT license as it allows any and all modifications. For help on adding a license see [this page](https://help.github.com/articles/adding-a-license-to-a-repository/)

**Comment by SeaRyanC** [comment]
Done. Thanks!

**Comment by SeaRyanC** [comment]
P.S. If you feel like taking over active development I'd be happy to deprecate this repro in favor of another fork

**Comment by keryja** [comment]
I most likely won't be adding many new features. But I'll gladly keep it working with the latest version of Factorio.

**Comment by keryja** [comment]
Just let me know when you can change it
